package InterFace1;


/**
* InterFace1/InterFace2Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/hp-pc/eclipse-workspace/Ass2/src/InterFace1.idl
* Saturday, 3 November, 2018 1:36:48 PM EDT
*/

public interface InterFace2Operations 
{
  String addCourse (String courseID, String semester);
  String removeCourse (String courseID, String semester);
  String listCourseAvailability (String semester);
  String enrolCourse (String studentID, String courseID, String semester);
  String getClassSchedule (String studentID);
  String swapCourse (String studentID, String newcourseID, String oldcourseID);
  String dropCourse (String studentID, String courseID);
  void courseCapacity (float Capacity);
  void UserId (String id);
} // interface InterFace2Operations
