package InterFace1;

/**
* InterFace1/InterFace2Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/hp-pc/eclipse-workspace/Ass2/src/InterFace1.idl
* Saturday, 3 November, 2018 1:36:48 PM EDT
*/

public final class InterFace2Holder implements org.omg.CORBA.portable.Streamable
{
  public InterFace1.InterFace2 value = null;

  public InterFace2Holder ()
  {
  }

  public InterFace2Holder (InterFace1.InterFace2 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InterFace1.InterFace2Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InterFace1.InterFace2Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InterFace1.InterFace2Helper.type ();
  }

}
