package InterFace1;


/**
* InterFace1/InterFace2POA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/hp-pc/eclipse-workspace/Ass2/src/InterFace1.idl
* Saturday, 3 November, 2018 1:36:48 PM EDT
*/

public abstract class InterFace2POA extends org.omg.PortableServer.Servant
 implements InterFace1.InterFace2Operations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addCourse", new java.lang.Integer (0));
    _methods.put ("removeCourse", new java.lang.Integer (1));
    _methods.put ("listCourseAvailability", new java.lang.Integer (2));
    _methods.put ("enrolCourse", new java.lang.Integer (3));
    _methods.put ("getClassSchedule", new java.lang.Integer (4));
    _methods.put ("swapCourse", new java.lang.Integer (5));
    _methods.put ("dropCourse", new java.lang.Integer (6));
    _methods.put ("courseCapacity", new java.lang.Integer (7));
    _methods.put ("UserId", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // InterFace1/InterFace2/addCourse
       {
         String courseID = in.read_string ();
         String semester = in.read_string ();
         String $result = null;
         $result = this.addCourse (courseID, semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // InterFace1/InterFace2/removeCourse
       {
         String courseID = in.read_string ();
         String semester = in.read_string ();
         String $result = null;
         $result = this.removeCourse (courseID, semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // InterFace1/InterFace2/listCourseAvailability
       {
         String semester = in.read_string ();
         String $result = null;
         $result = this.listCourseAvailability (semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // InterFace1/InterFace2/enrolCourse
       {
         String studentID = in.read_string ();
         String courseID = in.read_string ();
         String semester = in.read_string ();
         String $result = null;
         $result = this.enrolCourse (studentID, courseID, semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // InterFace1/InterFace2/getClassSchedule
       {
         String studentID = in.read_string ();
         String $result = null;
         $result = this.getClassSchedule (studentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // InterFace1/InterFace2/swapCourse
       {
         String studentID = in.read_string ();
         String newcourseID = in.read_string ();
         String oldcourseID = in.read_string ();
         String $result = null;
         $result = this.swapCourse (studentID, newcourseID, oldcourseID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // InterFace1/InterFace2/dropCourse
       {
         String studentID = in.read_string ();
         String courseID = in.read_string ();
         String $result = null;
         $result = this.dropCourse (studentID, courseID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // InterFace1/InterFace2/courseCapacity
       {
         float Capacity = in.read_float ();
         this.courseCapacity (Capacity);
         out = $rh.createReply();
         break;
       }

       case 8:  // InterFace1/InterFace2/UserId
       {
         String id = in.read_string ();
         this.UserId (id);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:InterFace1/InterFace2:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public InterFace2 _this() 
  {
    return InterFace2Helper.narrow(
    super._this_object());
  }

  public InterFace2 _this(org.omg.CORBA.ORB orb) 
  {
    return InterFace2Helper.narrow(
    super._this_object(orb));
  }


} // class InterFace2POA
