package InterFace1;


/**
* InterFace1/InterFace2.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/hp-pc/eclipse-workspace/Ass2/src/InterFace1.idl
* Saturday, 3 November, 2018 1:36:48 PM EDT
*/

public interface InterFace2 extends InterFace2Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterFace2
