package InterFace1;


/**
* InterFace1/InterFace2Helper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/hp-pc/eclipse-workspace/Ass2/src/InterFace1.idl
* Saturday, 3 November, 2018 1:36:48 PM EDT
*/

abstract public class InterFace2Helper
{
  private static String  _id = "IDL:InterFace1/InterFace2:1.0";

  public static void insert (org.omg.CORBA.Any a, InterFace1.InterFace2 that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static InterFace1.InterFace2 extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (InterFace1.InterFace2Helper.id (), "InterFace2");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static InterFace1.InterFace2 read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_InterFace2Stub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, InterFace1.InterFace2 value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static InterFace1.InterFace2 narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof InterFace1.InterFace2)
      return (InterFace1.InterFace2)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      InterFace1._InterFace2Stub stub = new InterFace1._InterFace2Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static InterFace1.InterFace2 unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof InterFace1.InterFace2)
      return (InterFace1.InterFace2)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      InterFace1._InterFace2Stub stub = new InterFace1._InterFace2Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
